### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Biplab",
  "email": "biplab@gmail.com",
  "address": "Kathmandu",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2023-01-01"
}

###