### Creates a new patient entity
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Test123",
  "email": "test_billing123a@email.com",
  "address": "Kathmandu",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2023-01-01"
}

###